<?php

function queen_attack_menu() {
  $items['queen_attack'] = array(
    'title' => 'Queen Attack',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('queen_attack_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['queen_attack_result'] = array(
    'title' => 'Queen Attack Results',
    'page callback' => 'queen_attack_result_display',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function queen_attack_form() {
  $form['coordinate']['queen_x'] = array(
    '#title' => 'Queen X',
    '#type' => 'textfield',
    '#description' => t("Enter the Queen's x-coordinate"),
    '#element_validate' => array('element_validate_integer_positive', 'element_validate_range2'),
    '#required' => TRUE,
  );
  $form['coordinate']['queen_y'] = array(
    '#title' => 'Queen Y',
    '#type' => 'textfield',
    '#description' => t("Enter the Queen's y-coordinate"),
    '#element_validate' => array('element_validate_integer_positive', 'element_validate_range2'),
    '#required' => TRUE,
  );
  $form['coordinate']['position_x'] = array(
    '#title' => 'Position X',
    '#type' => 'textfield',
    '#description' => t("Enter the x-coordinate for the position to be tested"),
    '#element_validate' => array('element_validate_integer_positive', 'element_validate_range2'),
    '#required' => TRUE,
  );
  $form['coordinate']['position_y'] = array(
    '#title' => 'Position Y',
    '#type' => 'textfield',
    '#description' => t("Enter the y-coordinate for the position to be tested"),
    '#element_validate' => array('element_validate_integer_positive', 'element_validate_range2'),
    '#required' => TRUE,
  );
  $form['coordinate']['#tree'] = TRUE;

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Test',
  );
  return $form;
}

function element_validate_range2($element) {
    if ($element['#value'] > 8 ) {
        form_error($element, t('You can\'t make a move off of the board, nub!'));
    }
}

function queen_attack_form_validate($form, &$form_state) {
  if ($form_state['values']['coordinate']['queen_x'] === $form_state['values']['coordinate']['position_x'] && $form_state['values']['coordinate']['queen_y'] === $form_state['values']['coordinate']['position_y']) {
    form_set_error('coordinate', 'You cannot have the pieces in the same place, nub!');
  }
}

function queen_attack_form_submit($form, &$form_state) {
  $path = drupal_get_path('module', 'queen_attack');
  $image = $path . '/white_queen_chess_piece.jpg';

  $queen_x = $form_state['values']['coordinate']['queen_x'];
  $queen_y = $form_state['values']['coordinate']['queen_y'];
  $position_x = $form_state['values']['coordinate']['position_x'];
  $position_y = $form_state['values']['coordinate']['position_y'];
  if ($queen_x == $position_x || $queen_y == $position_y || abs($queen_x - $position_x) === abs($queen_y - $position_y)) {
    $result = "<h1 id='attacks'>Attackable<br><img src = '" . $image . "'></h1>";
  } else {
    $result = "<h1 id='fail'>Not Attackable</h1>";
  }
  $_SESSION['queen_attack'] = $result;
  $form_state['redirect'] = 'queen_attack_result';
}

function queen_attack_result_display() {
  return $_SESSION['queen_attack'];
}
